"""

IBM Ponder This Challenge August 2023

 Find the number of positive square-triangular numbers below 10^{100} (googol).

"""

#Euler formula to compute Triangular Square numbers
def N(k):
    return (((3+2*2**0.5)**k-(3-2*2**0.5)**k)/(4*2**0.5))**2

max=pow(10,100)

#Generated by watsonx / starcoder

#With ths following prompt

# N(k) is a python function that returns an integer value. Write a python loop that finds
# the first value after 1 for k that gives a value that is more than parameter param

def find_first_value_after_1_for_k_that_gives_a_value_that_is_more_than_param(param):
    k = 1
    while N(k) <= param:
        k += 1
    return k

#End of Generated by watsonx / starcoder

print(-1+find_first_value_after_1_for_k_that_gives_a_value_that_is_more_than_param(max))


"""

gives 66

"""



