// This model is generated by some OPL code out of CUBE+WISE==MORE
using CP;

range r=0..9;
range rwithout0=1..9;
dvar int C in rwithout0;
dvar int W in rwithout0;
dvar int M in rwithout0;
dvar int U in r;
dvar int B in r;
dvar int E in r;
dvar int I in r;
dvar int S in r;
dvar int O in r;
dvar int R in r;

dvar int CUBE;
dvar int WISE;
dvar int MORE;
dvar int ROI;

maximize ROI;
subject to {
CUBE+WISE==MORE;

CUBE == 1000*C+100*U+10*B+1*E;
WISE == 1000*W+100*I+10*S+1*E;
MORE == 1000*M+100*O+10*R+1*E;
ROI == 100*R+10*O+1*I;

allDifferent(append(C,U,B,E,W,I,S,M,O,R));
}

execute {
writeln("CUBE = ",CUBE);
writeln("WISE = ",WISE);
writeln("MORE = ",MORE);
writeln("ROI = ",ROI);
}
